### ISSUE TITLE
公式问题

### ISSUE THREAD

**Issue by mumukehao** [Cloudy1225/Awesome-Link-Prediction#1]
github的markdown latex有问题，$ 前后加空格才能正常显示latex。比如：$\alpha$是不行的，但是， $\alpha$ 就是可以的

**Comment by Cloudy1225** [comment]
Thank you for your suggestion! I tried the fix you recommended, but it doesn't seem to work when using it within tables. While adding spaces around the $ signs works for regular text, it still doesn't render correctly inside tables. I'll keep looking for a solution and will update the issue with any progress. Thanks again for your help!
